import cities  from 'src/statics/js/cities.json'
export const getDefaultState = () => {
  return {
    count: null,
    cities:cities,
  created: false,
  errors: new Map(),
  files: null,
  filesUploaded: false,
  agencies:[],
  filters: {
    balcony: null,
    bathroom_unit: null,
    building_type: null,
    category: 'Квартира',
    kitchen_space: null,
    lastFloor: null,
    layout: null,
    floorMin: null,
    floorMax: null,
    minFloorNumber:null,
    notFirstFloor:null,
    notLastFloor:null,
    parking_type: null,
    priceMax: null,
    priceMin: null,
    property_type: null,
    renovation: null,
    sortBy: null,
    squareMax: null,
    squareMin: null,
    stove: null,
    sub_locality_name: null,
    subtype: [],
    rooms_total:[],
    yearMax: null,
    yearMin: null
  },
  flat: {
    action: null,
    address: null,
    agentComission: null,
    agent_comission_fee: null,
    agent_comission_type: 0,
    agent_fee: null,
    balcony: '',
    bathroom_unit: null,
    build_year: null,
    building_type: null,
    category: null,
    coords: null,
    deal_status: null,
    description: null,
    email: null,
    floor: null,
    guarded_parking: null,
    guarded_territory:null,
    haggle:0,
    img_order: [],
    kitchen_furniture: null,
    kitchen_space: null,
    layout: null,
    layout_changed: null,
    latitude:null,
    longtitude:null,
    lift:null,
    living_space: null,
    mortgage:0,
    name: null,
    not_built: 0,
    parking_type: null,
    phone: null,
    price:null,
    property_type: null,
    renovation: '',
    room_furniture: null,
    rooms_total: null,
    sanuzel: '',
    service_lift: null,
    square: null,
    status: null,
    stove: null,
    sub_locality_name: null,
    total_floors: null,
    type: null,
    useProfile: 1,
    windows: null
  },
  flats: {},
  isEditing: false,
  photosLoaded: 0,
  photosTotal: 0,
  phoneValid:false,
  title: null,
  uploadStarted: false,
    subLocalities:[
      {label:'Железнодорожный', value:'Железнодорожный'},
      {label:'Индустриальный', value:'Индустриальный'},
      {label:'Кировский', value:'Кировский'},
      {label:'Краснофлотский', value:'Краснофлотский'},
      {label:'Центральный', value:'Центральный'},
      {label:'Пригород', value:'', readonly:true, disable:true},
      {label:'Западное | ЕАО', value:'Западное| ЕАО'},
      {label:'Северное | Воронеж 1,2,3, Нагорное', value:'Северное | Воронеж 1,2,3'},
      {label:'Восточное | Матвеевка, Сергеевка, Галкино', value:'Восточное | Матвеевка, Сергеевка, Галкино'},
      {label:'Южное | Ильинка, Корсаково, Влад-ое шоссе', value:'Южное | Ильинка, Корсаково, Влад-ое шоссе'},
    ],
    buildingTypes: [
      { label:'Кирпич',value:'Кирпич'},
      { label:'Монолит',value:'Монолит'},
      { label:'Панель',value:'Панель'},
      { label:'Кирпич-монолит',value:'Кирпич-монолит'},
      { label:'Блок',value:'Блок'}],
    parkingTypes: [
      { label:'Закрытая',value:'Закрытая'},
      { label:'Подземная',value:'Подземная'},
      { label:'Открытая',value:'Открытая'}],
    statuses: [{label:'Жилой фонд', value:'Жилой фонд'}, {label:'Апартаменты', value:'Апартаменты'}],
    layoutOptions: [
      { label: 'Раздельные', value: 'Раздельные' },
      { label: 'Смежно-раздельные', value: 'Смежно-раздельные' },
      { label: 'Проходные', value: 'Проходные' },
      { label: 'Свободная планировка', value: 'Свободная планировка' }
    ],
    balconyOptions: [{label:'1 балкон', value:'1 балкон'}, {label:'2 балкона', value:'2 балкона'}, {label:'1 лоджия', value:'1 лоджия'}, {label:'Нет', value:'Нет'}],
    stoveOptions: [
      { label: 'Газовая', value: 'Газовая' },
      { label: 'Электрическая', value: 'Электрическая' },
      { label: 'Газ + электричество', value: 'Газ + электричество' }
    ],
    renovationOptions: [{label:'Требуется ремонт', value:'Требуется ремонт'}, {label:'Косметический ремонт', value:'Косметический ремонт'}, {label:'Хорошее состояние ', value:'Хорошее состояние'}, {label:'Отличное состояние', value:'Отличное состояние'}],
    sanuzels: [{label:'Совмещённый', value:'Совмещённый'}, {label:'Раздельный', value:'Раздельный'}, {label:'Более одного', value:'Более одного'}],
    windowsOptions: [{label:'Во двор',value:'Во двор'}, {label:'На улицу',value:'На улицу'}, {label:'В обе стороны',value:'В обе стороны'}],
    bonusOptions: [ { label: 'Нет', value: 0 }, { label: 'Фиксированная сумма', value: 1 }, { label: 'Процент от сделки', value: 2 } ],
    deal_statuses: [
      {label:'Свободная продажа', value:'Свободная продажа'},
      {label:'Альтернатива',value:'Альтернатива'},
      {label:'Переуступка',value:'Переуступка'},],
}
}
// export default () => (
//   Object.assign({}, getDefaultState)
// )
export default getDefaultState()

export const defaultFilters =getDefaultState().filters
